import { requireTenant } from '@/lib/auth-gate';
import { loadUsage } from '@/lib/usage';
import { Badge, Empty, PageHeader, Section } from '@/components/ui';
import { UsageChart } from './UsageChart';

export const dynamic = 'force-dynamic';

export default async function UsagePage() {
  const tenant = await requireTenant();
  const { summary, perToken, recent } = await loadUsage(tenant.id);

  return (
    <div>
      <PageHeader
        title="Usage"
        description="Per-token message volume, token spend, and tool-call counts."
      />

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(4, 1fr)',
          gap: 12,
          marginBottom: 32,
        }}
      >
        <SummaryCard label="Messages this month" value={summary.thisMonth.messages.toLocaleString()} />
        <SummaryCard
          label="Input tokens"
          value={summary.thisMonth.inputTokens.toLocaleString()}
          hint="Sent to provider"
        />
        <SummaryCard
          label="Output tokens"
          value={summary.thisMonth.outputTokens.toLocaleString()}
          hint="Generated by provider"
        />
        <SummaryCard
          label="Tool calls"
          value={summary.thisMonth.toolCalls.toLocaleString()}
          hint="Webhook hits (deduped)"
        />
      </div>

      <Section title="Last 30 days">
        <UsageChart data={summary.last30Days.series} />
      </Section>

      <Section title="Per-token usage this month">
        {perToken.length === 0 ? (
          <Empty>No tokens yet.</Empty>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ background: 'var(--accent-soft)', textAlign: 'left' }}>
                <Th>Token</Th>
                <Th>Status</Th>
                <Th>Messages</Th>
                <Th>Cap</Th>
                <Th>Last used</Th>
              </tr>
            </thead>
            <tbody>
              {perToken.map((t) => (
                <tr key={t.tokenId} style={{ borderTop: '1px solid var(--border)' }}>
                  <Td>
                    <strong>{t.label}</strong>{' '}
                    <code style={{ color: 'var(--muted)', fontSize: 11 }}>
                      …{t.publicTokenSuffix}
                    </code>
                  </Td>
                  <Td>
                    {t.revoked ? <Badge tone="bad">revoked</Badge> : <Badge tone="good">active</Badge>}
                  </Td>
                  <Td>{t.thisMonth.toLocaleString()}</Td>
                  <Td>
                    {t.cap == null ? (
                      <span style={{ color: 'var(--muted)' }}>—</span>
                    ) : (
                      <CapBar used={t.thisMonth} cap={t.cap} />
                    )}
                  </Td>
                  <Td style={{ color: 'var(--muted)', fontSize: 11 }}>
                    {t.lastUsedAt ? timeAgo(t.lastUsedAt) : 'never'}
                  </Td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Section>

      <Section title="Recent events">
        {recent.length === 0 ? (
          <Empty>No traffic yet — go say hi in the Playground.</Empty>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ background: 'var(--accent-soft)', textAlign: 'left' }}>
                <Th>When</Th>
                <Th>Token</Th>
                <Th>Model</Th>
                <Th>Tokens</Th>
                <Th>Tool calls</Th>
              </tr>
            </thead>
            <tbody>
              {recent.map((e) => (
                <tr key={e.id} style={{ borderTop: '1px solid var(--border)' }}>
                  <Td style={{ color: 'var(--muted)' }}>{timeAgo(e.createdAt)}</Td>
                  <Td>{e.tokenLabel}</Td>
                  <Td>
                    <code style={{ fontSize: 11 }}>{e.model}</code>
                  </Td>
                  <Td>
                    {e.inputTokens.toLocaleString()} in / {e.outputTokens.toLocaleString()} out
                  </Td>
                  <Td>{e.toolCallCount}</Td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Section>
    </div>
  );
}

function SummaryCard({
  label,
  value,
  hint,
}: {
  label: string;
  value: string;
  hint?: string;
}) {
  return (
    <div
      style={{
        border: '1px solid var(--border)',
        borderRadius: 10,
        padding: 14,
        background: 'var(--bg)',
      }}
    >
      <div style={{ fontSize: 11, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: 0.5 }}>
        {label}
      </div>
      <div style={{ fontSize: 24, fontWeight: 600, marginTop: 4 }}>{value}</div>
      {hint && <div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 2 }}>{hint}</div>}
    </div>
  );
}

function CapBar({ used, cap }: { used: number; cap: number }) {
  const pct = Math.min(100, (used / cap) * 100);
  const tone = pct >= 100 ? '#dc2626' : pct >= 80 ? '#d97706' : 'var(--accent)';
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 140 }}>
      <div
        style={{
          flex: 1,
          height: 6,
          background: 'var(--border)',
          borderRadius: 999,
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            width: `${pct}%`,
            height: '100%',
            background: tone,
            transition: 'width 0.2s',
          }}
        />
      </div>
      <span style={{ fontSize: 11, color: 'var(--muted)' }}>
        {used.toLocaleString()} / {cap.toLocaleString()}
      </span>
    </div>
  );
}

function Th({ children }: { children: React.ReactNode }) {
  return (
    <th style={{ padding: '8px 12px', fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 0.5 }}>
      {children}
    </th>
  );
}

function Td({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return <td style={{ padding: '10px 12px', verticalAlign: 'middle', ...style }}>{children}</td>;
}

function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s ago`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}
